//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.GetNotification {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0", ConfigurationName="GetNotification.ruzdiGetNotificationPackageStateService_v1_1PortType")]
    public interface ruzdiGetNotificationPackageStateService_v1_1PortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fciit.ru/eis2/ruzdi/getNotificationPackageState", ReplyAction="//fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0/getNotificationPack" +
            "ageStateService/getNotificationPackageStateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfApp3.GetNotification.getNotificationPackageStateResponse getNotificationPackageState(WpfApp3.GetNotification.getNotificationPackageStateRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://fciit.ru/eis2/ruzdi/getNotificationPackageState", ReplyAction="//fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0/getNotificationPack" +
            "ageStateService/getNotificationPackageStateResponse")]
        System.Threading.Tasks.Task<WpfApp3.GetNotification.getNotificationPackageStateResponse> getNotificationPackageStateAsync(WpfApp3.GetNotification.getNotificationPackageStateRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0")]
    public enum packageStateType {
        
        /// <remarks/>
        RECIEVED,
        
        /// <remarks/>
        INCONTROL,
        
        /// <remarks/>
        PAYMENTWAITING,
        
        /// <remarks/>
        FAULT,
        
        /// <remarks/>
        INWORK,
        
        /// <remarks/>
        RESULT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0")]
    public partial class pledgeNotificationStatePackageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string packageIdField;
        
        private string uipField;
        
        private StateType packageStateCodeField;
        
        private pledgeNotificationStateListElementType[] pledgeNotificationStateListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string packageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
                this.RaisePropertyChanged("packageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uip {
            get {
                return this.uipField;
            }
            set {
                this.uipField = value;
                this.RaisePropertyChanged("uip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public StateType packageStateCode {
            get {
                return this.packageStateCodeField;
            }
            set {
                this.packageStateCodeField = value;
                this.RaisePropertyChanged("packageStateCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pledgeNotificationStateListElement", IsNullable=false)]
        public pledgeNotificationStateListElementType[] pledgeNotificationStateList {
            get {
                return this.pledgeNotificationStateListField;
            }
            set {
                this.pledgeNotificationStateListField = value;
                this.RaisePropertyChanged("pledgeNotificationStateList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0")]
    public partial class StateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0")]
    public partial class documentAndSignatureType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private documentTypeType documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public documentTypeType documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("documentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentTypeSpecified {
            get {
                return this.documentTypeFieldSpecified;
            }
            set {
                this.documentTypeFieldSpecified = value;
                this.RaisePropertyChanged("documentTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0")]
    public enum documentTypeType {
        
        /// <remarks/>
        Notification,
        
        /// <remarks/>
        RegistrationCertificate,
        
        /// <remarks/>
        RegistrationRejection,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0")]
    public partial class pledgeNotificationStateListElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string notificationIdField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string notificationId {
            get {
                return this.notificationIdField;
            }
            set {
                this.notificationIdField = value;
                this.RaisePropertyChanged("notificationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("documentAndSignature", typeof(documentAndSignatureType), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("notificationStateCode", typeof(StateType), Order=1)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNotificationPackageStateRequest", WrapperNamespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0", IsWrapped=true)]
    public partial class getNotificationPackageStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0", Order=0)]
        public string packageId;
        
        public getNotificationPackageStateRequest() {
        }
        
        public getNotificationPackageStateRequest(string packageId) {
            this.packageId = packageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getNotificationPackageStateResponse", WrapperNamespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0", IsWrapped=true)]
    public partial class getNotificationPackageStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0", Order=0)]
        public WpfApp3.GetNotification.packageStateType packageState;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fciit.ru/eis2/ruzdi/getNotificationPackageStateService/v1_0", Order=1)]
        public WpfApp3.GetNotification.pledgeNotificationStatePackageType pledgeNotificationStatePackage;
        
        public getNotificationPackageStateResponse() {
        }
        
        public getNotificationPackageStateResponse(WpfApp3.GetNotification.packageStateType packageState, WpfApp3.GetNotification.pledgeNotificationStatePackageType pledgeNotificationStatePackage) {
            this.packageState = packageState;
            this.pledgeNotificationStatePackage = pledgeNotificationStatePackage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ruzdiGetNotificationPackageStateService_v1_1PortTypeChannel : WpfApp3.GetNotification.ruzdiGetNotificationPackageStateService_v1_1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ruzdiGetNotificationPackageStateService_v1_1PortTypeClient : System.ServiceModel.ClientBase<WpfApp3.GetNotification.ruzdiGetNotificationPackageStateService_v1_1PortType>, WpfApp3.GetNotification.ruzdiGetNotificationPackageStateService_v1_1PortType {
        
        public ruzdiGetNotificationPackageStateService_v1_1PortTypeClient() {
        }
        
        public ruzdiGetNotificationPackageStateService_v1_1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ruzdiGetNotificationPackageStateService_v1_1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ruzdiGetNotificationPackageStateService_v1_1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ruzdiGetNotificationPackageStateService_v1_1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp3.GetNotification.getNotificationPackageStateResponse WpfApp3.GetNotification.ruzdiGetNotificationPackageStateService_v1_1PortType.getNotificationPackageState(WpfApp3.GetNotification.getNotificationPackageStateRequest request) {
            return base.Channel.getNotificationPackageState(request);
        }
        
        public WpfApp3.GetNotification.packageStateType getNotificationPackageState(string packageId, out WpfApp3.GetNotification.pledgeNotificationStatePackageType pledgeNotificationStatePackage) {
            WpfApp3.GetNotification.getNotificationPackageStateRequest inValue = new WpfApp3.GetNotification.getNotificationPackageStateRequest();
            inValue.packageId = packageId;
            WpfApp3.GetNotification.getNotificationPackageStateResponse retVal = ((WpfApp3.GetNotification.ruzdiGetNotificationPackageStateService_v1_1PortType)(this)).getNotificationPackageState(inValue);
            pledgeNotificationStatePackage = retVal.pledgeNotificationStatePackage;
            return retVal.packageState;
        }
        
        public System.Threading.Tasks.Task<WpfApp3.GetNotification.getNotificationPackageStateResponse> getNotificationPackageStateAsync(WpfApp3.GetNotification.getNotificationPackageStateRequest request) {
            return base.Channel.getNotificationPackageStateAsync(request);
        }
    }
}
