//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3.UploadNotification {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0", ConfigurationName="UploadNotification.ruzdiUploadNotificationPackageService_v1_1PortType")]
    public interface ruzdiUploadNotificationPackageService_v1_1PortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService", ReplyAction="//fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0/uploadNotificationPac" +
            "kageService/uploadNotificationPackageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfApp3.UploadNotification.uploadNotificationPackageResponse uploadNotificationPackage(WpfApp3.UploadNotification.uploadNotificationPackageRequest request);
        
        // CODEGEN: Идет формирование контракта на сообщение, так как операция может иметь много возвращаемых значений.
        [System.ServiceModel.OperationContractAttribute(Action="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService", ReplyAction="//fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0/uploadNotificationPac" +
            "kageService/uploadNotificationPackageResponse")]
        System.Threading.Tasks.Task<WpfApp3.UploadNotification.uploadNotificationPackageResponse> uploadNotificationPackageAsync(WpfApp3.UploadNotification.uploadNotificationPackageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0")]
    public partial class pledgeNotificationPackageType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string packageIdField;
        
        private string uipField;
        
        private senderTypeType senderTypeField;
        
        private pledgeNotificationListElementType[] pledgeNotificationListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string packageId {
            get {
                return this.packageIdField;
            }
            set {
                this.packageIdField = value;
                this.RaisePropertyChanged("packageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string uip {
            get {
                return this.uipField;
            }
            set {
                this.uipField = value;
                this.RaisePropertyChanged("uip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public senderTypeType senderType {
            get {
                return this.senderTypeField;
            }
            set {
                this.senderTypeField = value;
                this.RaisePropertyChanged("senderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pledgeNotificationListElement", IsNullable=false)]
        public pledgeNotificationListElementType[] pledgeNotificationList {
            get {
                return this.pledgeNotificationListField;
            }
            set {
                this.pledgeNotificationListField = value;
                this.RaisePropertyChanged("pledgeNotificationList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0")]
    public enum senderTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0")]
    public partial class pledgeNotificationListElementType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string notificationIdField;
        
        private byte[] documentAndSignatureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string notificationId {
            get {
                return this.notificationIdField;
            }
            set {
                this.notificationIdField = value;
                this.RaisePropertyChanged("notificationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] documentAndSignature {
            get {
                return this.documentAndSignatureField;
            }
            set {
                this.documentAndSignatureField = value;
                this.RaisePropertyChanged("documentAndSignature");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0")]
    public partial class StateType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadNotificationPackageRequest", WrapperNamespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0", IsWrapped=true)]
    public partial class uploadNotificationPackageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0", Order=0)]
        public WpfApp3.UploadNotification.pledgeNotificationPackageType pledgeNotificationPackage;
        
        public uploadNotificationPackageRequest() {
        }
        
        public uploadNotificationPackageRequest(WpfApp3.UploadNotification.pledgeNotificationPackageType pledgeNotificationPackage) {
            this.pledgeNotificationPackage = pledgeNotificationPackage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadNotificationPackageResponse", WrapperNamespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0", IsWrapped=true)]
    public partial class uploadNotificationPackageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0", Order=0)]
        public string registrationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fciit.ru/eis2/ruzdi/uploadNotificationPackageService/v1_0", Order=1)]
        public WpfApp3.UploadNotification.StateType packageStateCode;
        
        public uploadNotificationPackageResponse() {
        }
        
        public uploadNotificationPackageResponse(string registrationId, WpfApp3.UploadNotification.StateType packageStateCode) {
            this.registrationId = registrationId;
            this.packageStateCode = packageStateCode;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ruzdiUploadNotificationPackageService_v1_1PortTypeChannel : WpfApp3.UploadNotification.ruzdiUploadNotificationPackageService_v1_1PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ruzdiUploadNotificationPackageService_v1_1PortTypeClient : System.ServiceModel.ClientBase<WpfApp3.UploadNotification.ruzdiUploadNotificationPackageService_v1_1PortType>, WpfApp3.UploadNotification.ruzdiUploadNotificationPackageService_v1_1PortType {
        
        public ruzdiUploadNotificationPackageService_v1_1PortTypeClient() {
        }
        
        public ruzdiUploadNotificationPackageService_v1_1PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ruzdiUploadNotificationPackageService_v1_1PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ruzdiUploadNotificationPackageService_v1_1PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ruzdiUploadNotificationPackageService_v1_1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp3.UploadNotification.uploadNotificationPackageResponse WpfApp3.UploadNotification.ruzdiUploadNotificationPackageService_v1_1PortType.uploadNotificationPackage(WpfApp3.UploadNotification.uploadNotificationPackageRequest request) {
            return base.Channel.uploadNotificationPackage(request);
        }
        
        public string uploadNotificationPackage(WpfApp3.UploadNotification.pledgeNotificationPackageType pledgeNotificationPackage, out WpfApp3.UploadNotification.StateType packageStateCode) {
            WpfApp3.UploadNotification.uploadNotificationPackageRequest inValue = new WpfApp3.UploadNotification.uploadNotificationPackageRequest();
            inValue.pledgeNotificationPackage = pledgeNotificationPackage;
            WpfApp3.UploadNotification.uploadNotificationPackageResponse retVal = ((WpfApp3.UploadNotification.ruzdiUploadNotificationPackageService_v1_1PortType)(this)).uploadNotificationPackage(inValue);
            packageStateCode = retVal.packageStateCode;
            return retVal.registrationId;
        }
        
        public System.Threading.Tasks.Task<WpfApp3.UploadNotification.uploadNotificationPackageResponse> uploadNotificationPackageAsync(WpfApp3.UploadNotification.uploadNotificationPackageRequest request) {
            return base.Channel.uploadNotificationPackageAsync(request);
        }
    }
}
